#Third party api config
fakeStore:
  api:
    url: "https://fakestoreapi.com"
    paths:
      products: "/products"

#Server config
server:
  port: 8080
  error:
    include-stacktrace: never

#Spring JPA config

spring:
  flyway:
      enabled: true
      locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/sep23productservice
    username: root
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always

