#Third party api config
fakeStore:
  api:
    url: "https://fakestoreapi.com"
    paths:
      products: "/products"

#Server config
server:
  port: 3000
  error:
    include-stacktrace: never

#Spring JPA config

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}

  logging:
    level:
      org.springframework.security: trace
      root: debug
  data:
    redis:
      host: localhost
      port: 6379


opensearch:
  uris: {AWS_OPENSEARCH_URI}
  username: {AWS_OPENSEARCH_USERNAME}
  password: {AES_OPENSEARCH_PASSWORD}
